### ISSUE TITLE
M的refinement如何实现的？

### ISSUE THREAD

**Issue by FANzhaoxin666** [JeremyWANGJZ/Category-6D-Pose#2]
同学你好，
   我阅读你的论文发现你的工作做有一个对M求残差，然后用矩阵乘法refine的过程？但是我SPD中的M，是一个B*N1*N2的矩阵，N1为观测点云点数，N2为类别先验点数，两个点数可以不一样，只是SPD中恰好都为1024而已。请问您是怎么构建M的？是和SPD中一样吗？如果是的话delta_M，是B*N1*N2还是B*N1*N1还是B*N2*N2？是直接用delta_M和M做矩阵乘法更新M吗？

**Comment by SocialGoodAI** [comment]
Hi Zhaoxin,

Thanks for you raise the valuable question. In our implementation, we build a delta_M with (B, N1, N2) due to N1=N2, which will bring a problem when N1 !=N2. In the experiment, we use torch.bmm(M, delta_M) to update the M, thus the matrix dimension of delta_M should be (B, N2, N2) if N1 !=N2.
